"""Encode the original numeral artwork as monochrome rows. Requires Pillow."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
FILES = ['0', '1-v3', '2', '3', '4-v2', '5-v2', '6-v5', '7-v2', '8', '9-v4']
lines = ['// Generated by tools/generate_time_digits.py from the original artwork.',
         '#pragma once', '#include <stdint.h>',
         'static const uint8_t DIGIT_WIDTHS[10] = {46,29,46,46,46,46,46,46,46,46};',
         'static const uint8_t DIGIT_ROWS[10][71][6] = {']
for name in FILES:
    im = Image.open(ROOT / ('resources/images/num-lg-' + name + '.png')).convert('RGBA')
    lines.append('  {')
    for y in range(71):
        row = [0] * 6
        for x in range(im.width):
            r, g, b, a = im.getpixel((x, y))
            if a >= 128 and r >= 128:
                row[x // 8] |= 1 << (x % 8)
        lines.append('    {' + ','.join(str(v) for v in row) + '},')
    lines.append('  },')
lines.append('};')
(ROOT / 'src/c/time_digits.h').write_text('\n'.join(lines) + '\n')
